FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /

COPY . ./
RUN dotnet restore "./EventNexus/EventNexus.csproj"
RUN dotnet publish "./EventNexus/EventNexus.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
SHELL ["bash"]
EXPOSE 80/tcp
WORKDIR /app
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "EventNexus.dll", "--urls", "http://0.0.0.0:5000"]
